BookStoreApp/Controllers/ProductController.cs
using VirginMegastoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace VirginMegastoreApp.Controllers
{
    public class ProductController : Controller
    {

        private readonly AppDbContext ctx;

        public ProductController(AppDbContext ctx)
        {
            this.ctx = ctx;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categoriesList = new SelectList(ctx.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CatList = categoriesList;
            return View();
        }

        [HttpPost]
        [Authorize(Roles ="Adminstrator")]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                ctx.Products.Add(product);
                ctx.SaveChanges();
                //upload file and update file name in table 
                if (product.ImageFile != null)
                {
                    string newFileName = uploadPhoto(product);

                    // update CoverPhotoName in database table
                    product.CoverPhoto = newFileName;
                    ctx.Products.Update(product);
                    ctx.SaveChanges();
                }

                //pass the ID of the newly created products to the details act 
                return Redirect("/Search/Detail/" + product.Product_ID);
            }
            var categoriesList = new SelectList(ctx.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CatList = categoriesList;
            return View();
        }

        private string uploadPhoto(Product product)
        {
            int productid = product.Product_ID;
            //upload photo
            string uplaodsFolder = "wwwroot/images/";
            //change filename to a unique name picxx.filetype
            string uniqueFilename = "pic" + productid + Path.GetExtension(product.ImageFile.FileName);
            string filePath = uplaodsFolder + uniqueFilename;
            //upload photo to folder
            product.ImageFile.CopyTo(new FileStream(filePath, FileMode.Create));
            return uniqueFilename;
        }

        [HttpPost]
        [Authorize(Roles = "Member")]
        [ValidateAntiForgeryToken]
        public IActionResult AddReview(Review review)
        {
            review.ReviewDate = DateTime.Now;
            ctx.Reviews.Add(review);
            ctx.SaveChanges();
            return Redirect("/Search/Detail/" + review.Product_ID);
        }

        [HttpGet]
        [Authorize(Roles = "Adminstrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest(); //must use global exeception handling to redirect to custom error page
            }
            Product product = ctx.Products.Find(id);//find the products with the given ID

            if (product == null)
            {
                return NotFound(); // must use global exeption handling to redirect user custom error page
            }

            var categoriesList = new SelectList(ctx.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CatList = categoriesList;
            return View(product);

        }

        [HttpPost]
        [Authorize(Roles = "Adminstrator")]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                //--------------- if a new photo was selected ------ //
                if (product.ImageFile != null)
                {
                    string newFileName = uploadPhoto(product);
                    product.CoverPhoto = newFileName;
                }
                // -------- update CoverPhotoName in database table ----------

                ctx.Products.Update(product);
                ctx.SaveChanges();
                //redirect the user to the Details View and pass the products id of current products
                return Redirect("/Search/Detail/" + product.Product_ID);
            }
            return View(product);

        }

        [HttpGet]
        [Authorize(Roles = "Adminstrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest(); //must use global exeception handling to redirect to custom error page
            }
            Product product = ctx.Products.Find(id);

            if (product == null)
            {
                return NotFound(); // must use global exeption handling to redirect user custom error page
            }

            var categoriesList = new SelectList(ctx.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CatList = categoriesList;
            return View(product);

        }

        [HttpPost]
        [Authorize(Roles = "Adminstrator")]
        public IActionResult Delete(Product product)
        {
            //delete the coverphoto from the filesystem
            if (product.CoverPhoto == null || product.CoverPhoto != "noimage.jpg")
            {
                string uploadsFolder = "wwwroot/images/";
                string uniqueFilename = product.CoverPhoto;
                FileInfo file = new FileInfo(uploadsFolder + uniqueFilename);
                if (file.Exists)//check file exsit or not  
                {
                    file.Delete();

                }
            }
            ctx.Products.Remove(product);
            ctx.SaveChanges();
            //redirect the user search page
            return Redirect("/Search/ProductByCategory/");

        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookStoreApp/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using VirginMegastoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace VirginMegastoreApp.Controllers
{
    public class SearchController : Controller
    {
        private readonly AppDbContext ctx;

        public SearchController(AppDbContext ctx)
        {
            this.ctx = ctx;
        }
  
        public IActionResult ProductByName(string? product_name)
        {
            if (String.IsNullOrEmpty(product_name))
            {
                // no title provided, display the view
                return View();
            }
            //when a title is provided retrieve the books that contain the title
            var products = ctx.Products
                          .Where(b => b.Product_Name.Contains(product_name))
                          .Include(b => b.Category) //eager loading, performs SQL join to get category details
                          .ToList();
            //return View(books);
            return PartialView("_PartialSearchResult", products);

        }
        public IActionResult ProductByCategory(int? catID)
        {   //first time page is requested, no catID will be provided
            if (catID == null || catID == 0)
            {   //to display a dropdown list of categories in the view
                var categoriesList = new SelectList(ctx.Categories.ToList(), "CategoryID", "CategoryName");
                ViewBag.CatList = categoriesList;
                return View();
            }
            //when an ID is provided read the books that contain the title and return the result
            var products = ctx.Products
                          .Where(b => b.CategoryID == catID)
                          .Include(b => b.Category) //eager loading, performs SQL join to get category details
                          .ToList();
            return PartialView("_PartialSearchResult", products);

        }
        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            //eager loading
            Product product = ctx.Products.Where(b => b.Product_ID == id)
                                 .Include(b => b.Category) //join with Category table
                                 .Include(b => b.Reviews) //Join with Reviews table
                                 .FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            //view is returned only when there is a record to display
            return View(product);

        }
    }
}

BookStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreApp</title>
    <link rel="stylesheet" href="~/css/newglyphicon.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStoreApp.styles.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Virgin Store App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item dropdown show">
                            <a class="dropdown-toggle nav-link text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Search Products</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Search" asp-action="ProductByName">By Name</a>
                                <a class="dropdown-item" asp-controller="Search" asp-action="ProductByCategory">By Category</a>
                             </div>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                            if(User.IsInRole("Adminstrator")){
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Product" asp-action="Create">Add New Product</a>
                                </li>
                            }
                      
                       
                        

                        <ul class="navbar-nav ml-auto" style="float:right">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">
                                        Register
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="login">
                                        Login
                                    </a>
                                </li>
                            }
                            else{

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="logout">
                                        Logout @User.Identity.Name
                                    </a>
                                </li>
                            }
                            
                        </ul>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_ValidationScriptsPartial">
</body>
</html>